### ISSUE TITLE
Question on collisionchecking (OpenRAVE)

### ISSUE THREAD

**Issue by aprath1** [SilviaSapora/dex-net-silvia#1]
Hi @SilviaSapora ,

Thank you for open sourcing the code! I am working on a robotic grasping project and trying now to generate database for grasping using dex-net and also to generate gqcnn dataset. 

Could you please let me know if you utilized collision checking in your implementation? I noticed in your code that the _src/dexnet/grasping/collision_checker.py (-> 'GraspCollisionChecker')_ is not available in this implementation.  The same function ('GraspCollisionChecker') is not imported but is still active (not commented out) in the file tools/generate_gqcnn_dataset.py.

If you actually used collision checking could you kindly let me know the version or branch of Mody and Ravelin you used to get the Openrave (from 'jeffmahler' ) installed in your system. I am getting errors specially due to Moby and Ravelin dependencies of Openrave not being compatible.

Thank you in advance.

**Comment by SilviaSapora** [comment]
Hi @aprath1, sorry for the late reply ! Thank you for your comment, sorry but I don't think I'll be able to help much here, I wrote this code 3 years ago and really don't remember.
With that being said, to generate grasp quality information for the datasets, you do need collision checking, so I am sure I did use it, but also there were multiple version of collision checking that were available (from what I remember), so maybe you could try using a different one? 
If a whole file is missing (compared to the original dex-net implementation), I would suspect I probably made a mistake when uploading the repo on git (sorry, I don't have access to the original repo atm as it's on an old laptop I don't have with me).
By looking at the file history of `tools/generate_gqcnn_dataset.py` I think I can confirm I was definitely using the collision checking (I commented and uncommented out some of the collision checking code).
I'll update you on which version of Mody and Ravelin I had when I have access to my old laptop (in a week or so), unless you solved the problem before then.

**Comment by aprath1** [comment]
Hi @SilviaSapora ,

Thank you for responding! I was actually able to resolve the issue related to installing openrave, seems like there was a bug in the jeffmahler/openrave implementation. An unused import of Eulerintegrator.h in plugins/mobyrave/mobyphysics.h was causing the build error, by removing this, build worked successfully (used master of Ravelin and Moby).
Thanks again
